### ISSUE TITLE
use in emacs?

### ISSUE THREAD

**Issue by mihem** [lionel-/codegrip#14]
Very useful tool. 

The readme talks about ".. and Emacs commands for reshaping R code". 

@lionel- How can codegrip be integrated in Emacs/ESS? Maybe 1-2 sentenced in the Readme would be greatly appreciated!

Thanks.

**Comment by lionel-** [comment]
You can install this file: https://github.com/lionel-/codegrip/blob/main/inst/emacs/codegrip.el

**Comment by mihem** [comment]
Thanks for the fast reply, great. I think it would be useful for ESS users, if this info is added in the readme.

In doom I had to add:
```
(package! codegrip :recipe (:host github
                            :repo "lionel-/codegrip"
                            :files ("inst/emacs/codegrip.el")))
```
to packages.el

Now it works great. It really like the codegrip-reshape function. It takes a second or so to execute, and doesn't work for regions. But apart from that everything works great.
